rvm:
  - 1.8.7
  - 1.9.2

before_script:
  - "mv -f config/database.travis.yml config/database.yml"
  - "psql -c 'create database lilion_test;' -U postgres >/dev/null"

script: "bundle exec rake db:drop db:create db:migrate test"

notifications:
  recipients:
    - dev@ekylibre.org